### ISSUE TITLE
ServerSession.set with a $ causes errors

### ISSUE THREAD

**Issue by mroftalp** [matteodem/meteor-server-session#11]
`
ServerSession.set('filter', , {name: 'default', value: {$or: [{createdBy: currentUser}, {assignedTo: currentUser}], deleted: false}});
`

`Exception while invoking method 'serversession_set' Error: key $or must not start with '$'`

**Comment by mroftalp** [comment]
@matteodem

**Comment by matteodem** [comment]
seems like mongodb cannot save documents that have keys starting with a `$` sign. http://stackoverflow.com/questions/8984162/weird-behavior-with-mongodb-fields-start-with
