### ISSUE TITLE
problem with multi user login at the same time.

### ISSUE THREAD

**Issue by yuomtheara** [matteodem/meteor-server-session#3]
When multi user login at the same time, don't work correctly.

**Comment by matteodem** [comment]
This session is for app wide constants, for example app name or anything else that you want to have stored on the server side.

**Comment by yuomtheara** [comment]
i think that it is like php session, when one user login set `name=A`, and then other user login set `name=B` at the same time.

**Comment by matteodem** [comment]
You can define different keys per user, but that's not really a good use case. For user based data you can always use the Meteor.users collection, see http://docs.meteor.com/#/full/meteor_users

**Comment by yuomtheara** [comment]
very thanks.
