### ISSUE TITLE
i should use ServerSession on client or server?

### ISSUE THREAD

**Issue by yuomtheara** [matteodem/meteor-server-session#4]
i should use ServerSession on client or server?

**Comment by matteodem** [comment]
you can use it on the client, with a "setCondition" check on the server.

**Comment by yuomtheara** [comment]
Thanks.
i do need use server session like php, but i don't understand on Meteor.user collection.

**Comment by matteodem** [comment]
If you have a look at all the tutorials it shouldn't be too much of a problem. Much success!

**Comment by yuomtheara** [comment]
thanks again.
