### ISSUE TITLE
use case example

### ISSUE THREAD

**Issue by the1mills** [matteodem/meteor-server-session#6]
In your GitHub documentation - could you please offer a simple use case scenario, for example:

(1) when and where it would be better to use a server side Session instead of a client Session

(2) how serverside Session is different than client-side Session.

(3) where there could possibly be some inconsistency/developer confusion between server side Session and client side Session.

thanks :)

**Comment by matteodem** [comment]
yes, I've been thinking of doing this for some time now, thanks!

**Comment by the1mills** [comment]
sure thing thanks: )

On Mon, Feb 9, 2015 at 6:44 AM, Matteo De Micheli <notifications@github.com>
wrote:

> yes, I've been thinking of doing this for some time now, thanks!
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/matteodem/meteor-server-session/issues/6#issuecomment-73519410>
> .
>



-- 
Alexander D. Mills
(650)269-9502
preferred email address: alexander.d.mills@gmail.com

   - www.linkedin.com/pub/alexander-mills/b/7a5/418/

**Comment by everywhereis** [comment]
+1 for that :)

**Comment by dandv** [comment]
The navigation state of the same user logged in from multiple devices? But that could be stored in the user's profile.

**Comment by matteodem** [comment]
It is more of general site wide configuration.

**Comment by matteodem** [comment]
Added a simple description to the README.md to clearify the purpose of this package.
