### ISSUE TITLE
logic seems flawed if the intent is to simulate server session

### ISSUE THREAD

**Issue by streamnsight** [matteodem/meteor-server-session#9]
I thought ServerSession was to simulate a session object as in PHP, Pyramid or other web servers. This is not at all what it does...
An 'old fashioned' session object persists user specific session data between HTTP calls, ie each user session has its own data, persisted between calls.

Here the Collection holds values set on Server side, but these are shared across all users: 
If i set a ServerSession value on the server for UserA, the collection published as such, is also visible to UserB.
Worse, if User A's action triggers change of the value in the ServerSession, then User B sees the changed value as it is published to the client.

How is this any different than using a collection in general? 

A ServerSession object store should first 
1) stay on serverside (i.e. not publish to the client)
2) persist user specific data
3) prevent sharing data between users

To do so with Mongo Collections one would need to index the object with the userId as key (for SET), and refer to it with this userId (for GET) 
Or maybe just use the Meteor.users Collection for this purpose.

Did I just misinterpret the functionality of this package? If I did, I think the name is somewhat misleading.

**Comment by matteodem** [comment]
Yes, I think it's important to update the README.md to show what this package was or is supposed to do. see #6

**Comment by matteodem** [comment]
see #6
